version: '3'

services:
  db:
    image: mariadb:11.1
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8089:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
